export const MessageTypes = {
  HISTORY: 'HISTORY',
  MESSAGE: 'MESSAGE',
  USER_JOINED: 'USER_JOINED',
  USER_LEFT: 'USER_LEFT',
  GRANTED: 'GRANTED',
  DENIED: 'DENIED',
  ACCESS: 'ACCESS',
  SESSION_NOT_AVAILABLE: 'SESSION_NOT_AVAILABLE',
}

export const ErrorTypes = {
  ACCESS_DENIED: 'ACCESS_DENIED',
  CONNECTION_ERROR: 'CONNECTION_ERROR',
  SESSION_NOT_AVAILABLE: 'SESSION_NOT_AVAILABLE',
}
